// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {protocol} from '../models';

export function CheckAutoLogin():Promise<Record<string, string>>;

export function Connect(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<string>;

export function DownloadFile(arg1:string,arg2:string):Promise<void>;

export function GetAvatar(arg1:string):Promise<string>;

export function GetHistory():Promise<Array<protocol.Message>>;

export function GetMyFullID():Promise<string>;

export function SelectAndUpload():Promise<void>;

export function SendMessage(arg1:string):Promise<void>;

export function UpdateAvatarHash(arg1:string):Promise<void>;

export function UploadAvatar():Promise<string>;

export function WipeData():Promise<void>;
