// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckAutoLogin() {
  return window['go']['main']['App']['CheckAutoLogin']();
}

export function Connect(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['Connect'](arg1, arg2, arg3, arg4, arg5);
}

export function DownloadFile(arg1, arg2) {
  return window['go']['main']['App']['DownloadFile'](arg1, arg2);
}

export function GetAvatar(arg1) {
  return window['go']['main']['App']['GetAvatar'](arg1);
}

export function GetHistory() {
  return window['go']['main']['App']['GetHistory']();
}

export function GetMyFullID() {
  return window['go']['main']['App']['GetMyFullID']();
}

export function SelectAndUpload() {
  return window['go']['main']['App']['SelectAndUpload']();
}

export function SendMessage(arg1) {
  return window['go']['main']['App']['SendMessage'](arg1);
}

export function UpdateAvatarHash(arg1) {
  return window['go']['main']['App']['UpdateAvatarHash'](arg1);
}

export function UploadAvatar() {
  return window['go']['main']['App']['UploadAvatar']();
}

export function WipeData() {
  return window['go']['main']['App']['WipeData']();
}
